name: Déployer l'image Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Connecter à Docker Hub
        run: |
          echo ${{ secrets.DOCKER_USERNAME }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Télécharger l'image Docker depuis Docker Hub
        run: docker pull devops/social-service-api:latest

      - name: Exécuter l'image Docker
        run: docker run -d --name social-service-container devops/social-service-api:latest
